apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: xkappel/wac-project-ufe
    newName: xkappel/wac-project-ufe
    newTag: 1.0.7 # aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
  - name: xkappel/wac-api
    newName: xkappel/wac-api
    newTag: 1.0.2

replacements:
  - targets:
      - select:
          group: fe.milung.eu
          version: v1
          kind: WebComponent
          name: harkap-ambulance-ufe
        fieldPaths:
          - spec.hash-suffix
    source:
      version: v1
      kind: Deployment
      name: harkap-ambulance-ufe-deployment
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ":"
        index: 1
