apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: xkappel/wac-project-ufe
    newName: xkappel/wac-project-ufe # {"$imagepolicy":  "wac-hospital:wac-project-ufe:name"}
    newTag: main.20240501.0822 # {"$imagepolicy": "wac-hospital:wac-project-ufe:tag"}
  - name: milung/ufe-controller
    newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
    newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
  - name: xkappel/wac-api
    newName: xkappel/wac-api # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
    newTag: main.20240501.0825 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
